### PR TITLE
Beautify DTP

### LINKED ISSUE #729: Round active application highlight
When using dots for running indicator style, perhaps it would be nice to round the corners of the semi-transparent highlight background?

### LINKED ISSUE #1721: How to add some space between app icons and panel border?
Hello,
I'am trying to add some space (padding?) between the app icons and panel border of a vertical panel.
See the picture I've attached:

Panel

I've done it by editing: `.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js`
and changed the line:
```javascript
const panelSize = PanelSettings.getPanelSize(Me.settings, this.monitor.index);
```
to:
```javascript
const panelSize = PanelSettings.getPanelSize(Me.settings, this.monitor.index) + 12;
```

Then I added the following code to: `.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/stylesheet.css`

```css
#dashtopanelScrollview .dash-item-container > StWidget { 
	border-left: 6px;
	border-right: 6px;
}
```
It works just fine, but I wonder is there a more elegant way to achieve it? Maybe by only some css manipulations without editing the source code of `panel.js`?

Thank you in advance.

### LINKED ISSUE #2009: "Animate hovering app icons" animates the highlight background of a focused app instead of just the app icon itself
The focused app (highlighted background) (and running indicator) travel along with the app icon when hovered instead of just the app icon itself 
Background and the indicators should be static elements, they are not supposed to be moving at all, it breaks consistency

To reproduce:
DTP Settings -> Style -> Animate hovering app icons -> Travel (or any of the animation settings)

Current behavior:
image

Expected behavior:
image psd(5)

### PR DESCRIPTION
**Pull request by Hirnmoder**
Major changes
---
1. App icon highlighting unaffected by hover animation (Resolves #2009)
2. Allow hover animation travel below 0%
3. Allow hover animation zoom below 100%
4. Hover highlighting independent of hover animation
5. Custom color for hover highlighting
6. Custom color for mouse down highlighting
7. Icon background with rounded corners (Resolves #729 #1647 #1819)
8. Customize margin for app icons towards screen border and desktop (Resolves #1721 #1819)

Some visual impressions with custom settings
---
Change|Before|After
---|---|---
1|image|image
2,3|image|image
4|Either animation or highlighting|image
5|image|image
6|image|image
7|image|image
8|image|image

### CODE REVIEW

**Comment by Hirnmoder** [comment]
I've made accidentially a rebase instead of a fast-forward merge. This is why all the other commits show up. Merging should not be affected by this.
However, if you would like me to re-do the PR, just comment and I'll do it.

File: appIcons.js [hunk 1]
```diff
@@ -255,8 +269,14 @@ export const TaskbarAppIcon = GObject.registerClass({
             SETTINGS.connect('changed::group-apps-label-font-color-minimized', this._updateWindowTitleStyle.bind(this)),
             SETTINGS.connect('changed::group-apps-label-max-width', this._updateWindowTitleStyle.bind(this)),
             SETTINGS.connect('changed::group-apps-use-fixed-width', this._updateWindowTitleStyle.bind(this)),
-            SETTINGS.connect('changed::group-apps-underline-unfocused', this._settingsChangeRefresh.bind(this))
-        ]
+            SETTINGS.connect('changed::group-apps-underline-unfocused', this._settingsChangeRefresh.bind(this)),
+        ];
+
+        if (!this._checkGtkVersion_cssVariables()) {
+            this._dtpSettingsSignalIds += [
```
Comment (Arilas) [inline appIcons.js:276]: You are converting array into string

File: ui/BoxHighlightAppIconHoverOptions.ui [hunk 2]
```diff
@@ -0,0 +1,70 @@
+<?xml version="1.0" encoding="UTF-8"?>
```
Comment (Arilas) [inline ui/BoxHighlightAppIconHoverOptions.ui:1]: You forgot to add this file to `Makefile`

**Review by Arilas — CHANGES_REQUESTED** [review]
Hey. I've tried to use your PR locally and found some bugs. Some of them are commented here in review.

Also border radius is not working for hovering and active icons. I'm not sure why.

**Comment by Hirnmoder** [comment]
> Hey. I've tried to use your PR locally and found some bugs. Some of them are commented here in review.
> 
> Also border radius is not working for hovering and active icons. I'm not sure why.

Hey Arilas,
thank you for testing my PR :)

The border radius with active icon bug sounds suspicious. May I request your software stack? (so on which distribution of Linux did you test it and what was the version of GNOME?). I am still on Fedora 40 with GNOME 46 and no support for CSS variables. It is possible that my workaround-code for CSS variables works (GNOME <= 46), but my code for the actual implementation (GNOME >= 47) does not. I'll have to look into this.

For the other bugs in question, I'll leave a response directly at your code remarks.

File: ui/BoxHighlightAppIconHoverOptions.ui (hunk 2 above)
Comment (Hirnmoder) [reply ui/BoxHighlightAppIconHoverOptions.ui:1]: Good catch, will update :+1:

File: appIcons.js (hunk 1 above)
Comment (Hirnmoder) [reply appIcons.js:276]: I don't see your point here. `this._dtpSettingsSignalIds` is an array of integers (signal IDs to be precise) and I concatenate two arrays. It may be not the most elegant solution, but I can't see any array-to-string conversion (even implicitly) here.
Please advise

**Comment by HappyHippo77** [comment]
I can confirm that the border radius is not functioning for me. On top of that, neither is selecting a color for the highlight. Even setting it to white, disabling the extension, and/or relogging does not correct that, even though the settings remain the same. My system info is as follows:

OS: Arch Linux (rolling)
GNOME Version: 47
Windowing System: Wayland
Kernel Version: Linux 6.6.63-1-lts

Unfortunately I don't know very well how these things work, so I can't do much on my own to help with debugging. I can provide any information needed by request though.

**Comment by Hirnmoder** [comment]
> I can confirm that the border radius is not functioning for me. On top of that, neither is selecting a color for the highlight. Even setting it to white, disabling the extension, and/or relogging does not correct that, even though the settings remain the same. My system info is as follows:
> 
> OS: Arch Linux (rolling) GNOME Version: 47 Windowing System: Wayland Kernel Version: Linux 6.6.63-1-lts
> 
> Unfortunately I don't know very well how these things work, so I can't do much on my own to help with debugging. I can provide any information needed by request though.

Thank you for your bug report. It is likely that my implementation for GNOME 47 is just not working (correctly). I'll try to make some more updates as soon as I find some time to upgrade to GNOME 47. Unfortunately, the weeks before Christmas are always quite busy so I might not be able to fix the issue this year. I'll keep this thread updated.

**Comment by Hirnmoder** [comment]
Hey all,
thanks again for reporting the apparent bugs within my implementation.
I was able to reproduce the bugs with Fedora 41 and GNOME 47.

The main suspect is the usage of CSS variables in my code for GTK >= 4.16. Unfortunately, after digging around some time, I was not really able to locate why my usage does not work. Despite various announcements (see [1](https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6540), [2](https://blogs.gnome.org/alicem/2024/06/07/css-happenings/), [3](https://mk.nyaa.place/notes/9t8xd0oi6lio09xv), [4](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/css-variables.html)) it seems that using (custom) CSS variables within a GNOME extension does not work as expected.

This is why my "fix" for this issue is to simply keep using my workaround code for GTK < 4.16 until GNOME implements support for custom CSS variables even for extensions.

Happy Holidays

**Comment by hirsche** [comment]
I've tested it on

**Fedora 40** with
**Gnome 46**

and it works well for me. Definitly would recommend including it!!

File: appIcons.js (hunk 1 above)
Comment (Hirnmoder) [reply appIcons.js:276]: @Arilas
After digging around a bit, I must revise my previous statement. Apparently JavaScript handles some array functions differently from what I was expecting - and you were right. My code did indeed produce a string. Will fix ASAP.

I tried evaluating the expression `[1, 2, 3] + [4, 5, 6]` in a JS interpreter, and indeed, it produces `'1,2,34,5,6'` instead of what I originally anticipated.

**Comment by charlesg99** [comment]
Thanks! Testing your changes atm, I like it, but I get a bunch of `Ignoring length property that isn't a number` warnings when hovering over the icons. Seems like it's caused by the empty css variables in the stylesheet. Removing them stop the warnings.

I like the variable approach but honestly, if it doesn't work, I would remove all of it (we have enough dead code as it is :joy:)

**Comment by Hirnmoder** [comment]
As you suggested I removed all CSS variables-related code from this PR. It is probably better if the functionality gets merged without additional dead/future code. I'll just open another PR - marked as WIP - to re-add that CSS variable code in case GNOME starts supporting it soon. Doing so makes the improvements in this PR independent from the actual implementation and we can improve the code base at a later stage when it is possible to do so :)

**Comment by charlesg99** [comment]
Thanks! I think we're ready! 

One thing is that I wish you didn't include all the code format changes, or at least put it in a separate PR or something. Makes it harder to see the actual changes, but I understand that the code is a nightmare for people who like it nice and tidy :rofl:. I myself use "[prettier](https://prettier.io/)" in most of my projects, it works pretty good and never broke my code so that's a plus. Maybe I'll try to run it in dash to panel, this way we would have a "standard". Do you have experiences with other tools like that? 

Anyway thanks again!

**Comment by Hirnmoder** [comment]
> Thanks! I think we're ready!
> 
> One thing is that I wish you didn't include all the code format changes, or at least put it in a separate PR or something. Makes it harder to see the actual changes, but I understand that the code is a nightmare for people who like it nice and tidy 🤣. I myself use "[prettier](https://prettier.io/)" in most of my projects, it works pretty good and never broke my code so that's a plus. Maybe I'll try to run it in dash to panel, this way we would have a "standard". Do you have experiences with other tools like that?
> 
> Anyway thanks again!

Sorry for my delayed response.
I edited the code in VS Code using the default JavaScript formatter as described by Microsoft [1]. Additionally, I use an extension to remove all trailing whitespace [2], which otherwise would clutter a document and makes changes (especially big ones like this) a pain to merge. So far, both of them have been really helpful and I have not encountered a bug (yet).
However, if not developing with VS Code is a major requirement, establishing a well-supported and configurable formatter/linter is probably the best way forward. So using prettier is a valid option, too :)


[1] https://code.visualstudio.com/Docs/languages/javascript
[2] https://marketplace.visualstudio.com/items/?itemName=shardulm94.trailing-spaces
